#!/bin/bash
#this is an install script for AWS Redhat free EC2 instance

# AWS instance configuration:
#1. AMI: Amazon Linux AMI 2018.03.0 (HVM), SSD Volume Type - ami-0998bf58313ab53d
#2. Instance Type:  t2.micro => freetier eligible
#3. Configure Instance Details: **PASTE THIS FILE IN 'User data' text box; bottom of the page
#4. Add-Storage: add more than 16 GiB to Size GiB) text box
#5. Add Tags: nothing needed
#6. Configure Security Group: configure as following
#   Type        Protocal       Port Range     Source                        Description  
#   SSH         TCP            22             Anywhere:0.0.0.0/0, ::/0      Login
#   HTTP        TCP            80             Anywhere:0.0.0.0/0, ::/0      HTTP
#   Custom TCP  TCP            3838           Anywhere:0.0.0.0/0, ::/0      Shiny Server Default
#   Custim TCP  TCP            8787           Anywhere:0.0.0.0/0, ::/0      RStudio server Default
#7. Review
#8. Launch

#you may have to wait 20 minutes plus, for the install to catch up with all the installs.
#update lunix
yum -y update

#Note: Free version of AWS and R library ‘readr’, you need to create swap file.

#4GB swap file needed for R library 'readr'for free AWS instance
dd if=/dev/zero of=/swapfile bs=128M count=32

#1GB swap file
#dd if=/dev/zero of=swapfile bs=1M count=3000
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
swapon -s
echo "/swapfile swap swap defaults 0 0"|tee -a /etc/fstab

#‘leaflet’ library requires 'livpng-devel'.
yum install -y libpng-devel

#other libraries you may want to install in linux Just remove the ‘#’
#yum install -y nginx
#yum install -y gdebi-core
#yum install -y apache2-utils
#yum install -y pandoc
#yum install -y pandoc-citeproc
#yum install -y libssl-dev
#yum install -y libcurl4-gnutls-dev
#yum install -y libcairo2-dev
#yum install -y libgdal-dev
#yum install -y libgeos-dev
#yum install -y libxml2-dev
#yum install -y libxt-dev
#yum install -y ibv8-dev

#install R.
yum install -y R

#install RStudio-Server 1.2.5033 (2017-07-20)
wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.2.5033-x86_64.rpm
yum install -y --nogpgcheck rstudio-server-rhel-1.2.5033-x86_64.rpm
rm rstudio-server-rhel-1.2.5033-x86_64.rpm

#install shiny for installing shiny server
R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"

# Install other packages as you need. 
# These are the packages I want installed. remove the '#' for packages you want
#R -e "install.packages(c('adehabitatHR'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('dplyr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('data.table'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('DT'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('fasttime'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('ggthemes'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('ggExtra'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('geojsonio'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('highcharter'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('gridExtra'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('lazyeval'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('lubridate'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('leaflet'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('maptools'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('magrittr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('readr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('rgdal'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('rgeos'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('rmarkdown'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('shinydashboard'), repos='http://cran.rstudio.com/')"
R -e "install.packages(c('shinyjs'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('sp'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('stringr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('tidyr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('tidyr'), repos='http://cran.rstudio.com/')"
#R -e "install.packages(c('viridis'), repos='http://cran.rstudio.com/')"

#install shiny-server 1.5.13.944 (2020-03-21)
wget https://download3.rstudio.org/centos6.3/x86_64/shiny-server-1.5.13.944-x86_64.rpm
yum install -y --nogpgcheck shiny-server-1.5.13.944-x86_64.rpm
rm shiny-server-1.4.2.786-rh5-x86_64.rpm

#update redhat
yum install -y curl-devel

#set up user of shiny studio. Be sure to replace ‘mredthehorse’ with your own username
#replace ‘wwilburr’ with your own password
useradd mredthehorse
echo mredthehorse:wwilburr | chpasswd

#resources
#see https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/
#see https://tm3.ghost.io/2017/12/31/deploying-an-r-shiny-app-to-aws/
#see https://www.r-bloggers.com/shiny-server-on-aws/
#see https://www.youtube.com/watch?v=0h9VOQZX6QM&t=15s
#see https://www.youtube.com/watch?v=zJuFpqB01u4
